name: Build project

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
  UNITY_VERSION: 2022.3.46f1
  TARGET_PLATFORM: StandaloneWindows64

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - run: |
          docker pull unityci/editor:ubuntu-2022.3.46f1-windows-mono-3.1.0
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: jlumbroso/free-disk-space@main
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v4.4.3
        id: artifact-upload-step
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      - name: Notify Discord
        if: success()
        uses: stegzilla/discord-notify@v4
        with:
            webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
            title: "Build Report"
            message: "Build succeeded, artifact: ${{ steps.artifact-upload-step.outputs.artifact-url }}"
            avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
            username: GitHub
